"""baseline schema

Revision ID: 84056267de8a
Revises: 
Create Date: 2026-08-25 17:34:53.028709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84056267de8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('proto', sa.String(length=8), nullable=False),
    sa.Column('app_proto', sa.String(length=32), nullable=True),
    sa.Column('bytes_in', sa.Integer(), nullable=False),
    sa.Column('bytes_out', sa.Integer(), nullable=False),
    sa.Column('packets', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_dst_ip'), 'connections', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_connections_src_ip'), 'connections', ['src_ip'], unique=False)
    op.create_index(op.f('ix_connections_ts'), 'connections', ['ts'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('vendor_oui', sa.String(length=128), nullable=True),
    sa.Column('custom_name', sa.String(length=128), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('is_known', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=True)
    op.create_table('suricata_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('proto', sa.String(length=8), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suricata_events_dst_ip'), 'suricata_events', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_suricata_events_event_type'), 'suricata_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_suricata_events_src_ip'), 'suricata_events', ['src_ip'], unique=False)
    op.create_index(op.f('ix_suricata_events_ts'), 'suricata_events', ['ts'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_device_id', sa.Integer(), nullable=True),
    sa.Column('related_ip', sa.String(length=45), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['related_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_rule_key'), 'alerts', ['rule_key'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_ts'), 'alerts', ['ts'], unique=False)
    op.create_table('device_ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('proto', sa.String(length=8), nullable=False),
    sa.Column('service_guess', sa.String(length=64), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_ports_device_id'), 'device_ports', ['device_id'], unique=False)
    op.create_table('device_sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('ssid', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_sightings_device_id'), 'device_sightings', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_sightings_seen_at'), 'device_sightings', ['seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_sightings_seen_at'), table_name='device_sightings')
    op.drop_index(op.f('ix_device_sightings_device_id'), table_name='device_sightings')
    op.drop_table('device_sightings')
    op.drop_index(op.f('ix_device_ports_device_id'), table_name='device_ports')
    op.drop_table('device_ports')
    op.drop_index(op.f('ix_alerts_ts'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_key'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suricata_events_ts'), table_name='suricata_events')
    op.drop_index(op.f('ix_suricata_events_src_ip'), table_name='suricata_events')
    op.drop_index(op.f('ix_suricata_events_event_type'), table_name='suricata_events')
    op.drop_index(op.f('ix_suricata_events_dst_ip'), table_name='suricata_events')
    op.drop_table('suricata_events')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_connections_ts'), table_name='connections')
    op.drop_index(op.f('ix_connections_src_ip'), table_name='connections')
    op.drop_index(op.f('ix_connections_dst_ip'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
